image: docker:stable

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

services:
    - docker:dind


before_script:
    - docker info

build:
    script:
        - docker build -t opencv-python .
        - docker tag opencv-python:latest gruunday/opencv-python:latest

deploy:
    script:
        - docker login -u gruunday -p $DOCKERPASS
        - docker push gruunday/opencv-python:latest  
