version: 2
jobs:
  build:
    docker:
        - image: docker:stable

    environment:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2

    services:
        - doocker:dind

    steps:
      - checkout
      - run:
          name: Image Build
          command: docker build -t opencv-python3 .

      - run:
          name: Image Tag
          command: docker tag opencv-python:latest gruunday/opencv-python:latest
